package golang

import (
	"strings"
	"testing"

	"github.com/j75689/archon/internal/graph"
	"github.com/j75689/archon/internal/lang"
)

func snap(files map[string]string) lang.Snapshot {
	m := make(map[string][]byte, len(files))
	for k, v := range files {
		m[k] = []byte(v)
	}
	return lang.Snapshot{Rev: "HEAD", Files: m}
}

func TestMatchRequiresGoMod(t *testing.T) {
	var e Extractor
	if e.Match(snap(nil)) {
		t.Fatal("empty should not match")
	}
	if !e.Match(snap(map[string]string{"go.mod": "module example.com/m\n"})) {
		t.Fatal("go.mod should match")
	}
}

func TestExtractFirstPartyEdgesAndIsolatedNode(t *testing.T) {
	var e Extractor
	g, err := e.Extract(snap(map[string]string{
		"go.mod": "module example.com/m\n",
		"a.go":   "package m\nimport \"example.com/m/b\"\n",
		"b/b.go": "package b\n",
		"c/c.go": "package c\n",
	}))
	if err != nil {
		t.Fatal(err)
	}
	g, err = graph.Compile(g)
	if err != nil {
		t.Fatal(err)
	}
	keys := map[string]bool{}
	for _, n := range g.Nodes {
		keys[n.Key] = true
	}
	if !keys["example.com/m"] || !keys["example.com/m/b"] || !keys["example.com/m/c"] {
		t.Fatalf("nodes: %+v", g.Nodes)
	}
	if len(g.Edges) != 1 || g.Edges[0].From != "example.com/m" || g.Edges[0].To != "example.com/m/b" {
		t.Fatalf("edges: %+v", g.Edges)
	}
}

func TestExtractIgnoresStdlibVendorTestsGeneratedIgnore(t *testing.T) {
	var e Extractor
	g, err := e.Extract(snap(map[string]string{
		"go.mod":        "module example.com/m\n",
		"a.go":          "package m\nimport (\n\t\"fmt\"\n\t\"example.com/other\"\n)\nfunc hidden() {}\n",
		"a_test.go":     "package m\nimport \"example.com/m/secret\"\n",
		"vendor/x/x.go": "package x\n",
		"testdata/t.go": "package t\n",
		"gen.go":        "// Code generated by hand; DO NOT EDIT.\npackage m\nimport \"example.com/m/genpkg\"\n",
		"skip.go":       "//go:build ignore\n\npackage m\nimport \"example.com/m/skipped\"\n",
		"secret/s.go":   "package secret\n",
		"genpkg/g.go":   "package genpkg\n",
		"skipped/s.go":  "package skipped\n",
	}))
	if err != nil {
		t.Fatal(err)
	}
	if len(g.Edges) != 0 {
		t.Fatalf("expected no first-party edges, got %+v", g.Edges)
	}
}

func TestIgnoreTextInsideBodyStillParticipates(t *testing.T) {
	var e Extractor
	g, err := e.Extract(snap(map[string]string{
		"go.mod": "module example.com/m\n",
		"a.go": "package m\n" +
			"import \"example.com/m/b\"\n" +
			"func keep() string { return \"//go:build ignore\" }\n",
		"b/b.go": "package b\n",
	}))
	if err != nil {
		t.Fatal(err)
	}
	g, err = graph.Compile(g)
	if err != nil {
		t.Fatal(err)
	}
	if len(g.Edges) != 1 || g.Edges[0].From != "example.com/m" || g.Edges[0].To != "example.com/m/b" {
		t.Fatalf("edges: %+v", g.Edges)
	}
}

func TestIgnoreBuildConstraintExcludesEdges(t *testing.T) {
	var e Extractor
	g, err := e.Extract(snap(map[string]string{
		"go.mod": "module example.com/m\n",
		"a.go":   "//go:build ignore\n\npackage m\nimport \"example.com/m/b\"\n",
		"b/b.go": "package b\n",
	}))
	if err != nil {
		t.Fatal(err)
	}
	if len(g.Edges) != 0 {
		t.Fatalf("expected no edges, got %+v", g.Edges)
	}
}

func TestGeneratedCommentLaterInHeaderExcludesEdges(t *testing.T) {
	var e Extractor
	g, err := e.Extract(snap(map[string]string{
		"go.mod": "module example.com/m\n",
		"a.go": "//go:build linux\n" +
			"// Code generated by x; DO NOT EDIT.\n\n" +
			"package m\nimport \"example.com/m/b\"\n",
		"b/b.go": "package b\n",
	}))
	if err != nil {
		t.Fatal(err)
	}
	if len(g.Edges) != 0 {
		t.Fatalf("expected no edges, got %+v", g.Edges)
	}
}

func TestRenderMermaidDropsEdgesToGeneratedOrTestOnlyPackages(t *testing.T) {
	var e Extractor
	g, err := e.Extract(snap(map[string]string{
		"go.mod":             "module example.com/m\n",
		"a.go":               "package m\nimport (\n\t\"example.com/m/gen\"\n\t_ \"example.com/m/onlytest\"\n)\n",
		"gen/g.go":           "// Code generated by x; DO NOT EDIT.\npackage gen\n",
		"onlytest/t_test.go": "package onlytest\n",
	}))
	if err != nil {
		t.Fatal(err)
	}
	g, err = graph.Compile(g)
	if err != nil {
		t.Fatal(err)
	}

	got := graph.RenderMermaid(g)
	if strings.Contains(got, "--> \n") {
		t.Fatalf("rendered dangling edge: %q", got)
	}
	if strings.Contains(got, "example.com/m/gen") || strings.Contains(got, "gen\"]") {
		t.Fatalf("generated package must not be rendered: %q", got)
	}
	if strings.Contains(got, "example.com/m/onlytest") || strings.Contains(got, "onlytest\"]") {
		t.Fatalf("test-only package must not be rendered: %q", got)
	}
}

func TestBodyOnlyChangeSameGraph(t *testing.T) {
	var e Extractor
	a := snap(map[string]string{
		"go.mod": "module example.com/m\n",
		"a.go":   "package m\nfunc unexported() { println(1) }\n",
	})
	b := snap(map[string]string{
		"go.mod": "module example.com/m\n",
		"a.go":   "package m\nfunc unexported() { println(2) }\n",
	})
	ga, _ := graph.Compile(mustExtract(t, e, a))
	gb, _ := graph.Compile(mustExtract(t, e, b))
	if !graph.DiffGraphs(ga, gb).Empty() {
		t.Fatal("body-only change must not affect graph")
	}
}

func TestSyntaxError(t *testing.T) {
	var e Extractor
	_, err := e.Extract(snap(map[string]string{
		"go.mod": "module example.com/m\n",
		"a.go":   "package m\nfunc {",
	}))
	if err == nil {
		t.Fatal("expected parse error")
	}
	if !strings.Contains(err.Error(), "a.go") {
		t.Fatalf("path in error: %v", err)
	}
}

func mustExtract(t *testing.T, e Extractor, s lang.Snapshot) graph.Graph {
	t.Helper()
	g, err := e.Extract(s)
	if err != nil {
		t.Fatal(err)
	}
	return g
}
